// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Queries$FlowsUserApp from "../Queries.bs.js";
import EthereumBlockiesBase64 from "ethereum-blockies-base64";

function ContactsTable$Contacts(Props) {
  var contactsQuery = Props.contactsQuery;
  var match = contactsQuery.data;
  if (match === undefined && contactsQuery.loading) {
    return React.createElement("p", undefined, "Loading");
  }
  var error = contactsQuery.error;
  if (error !== undefined) {
    console.log(error);
    return React.createElement("p", undefined, "Data is loaded");
  } else if (match !== undefined) {
    return React.createElement("table", {
                className: "min-w-full divide-y divide-gray-200"
              }, React.createElement("thead", {
                    className: "bg-black"
                  }, React.createElement("tr", undefined, React.createElement("th", {
                            className: "px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider",
                            scope: "col"
                          }, "Name"), React.createElement("th", {
                            className: "px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider",
                            scope: "col"
                          }, "Description"), React.createElement("th", {
                            className: "relative px-6 py-3",
                            scope: "col"
                          }, React.createElement("span", {
                                className: "sr-only"
                              }, "Edit")))), Belt_Array.map(match.user, (function (contact) {
                      return React.createElement("tbody", {
                                  className: "bg-white divide-y divide-gray-200"
                                }, React.createElement("tr", undefined, React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap"
                                        }, React.createElement("div", {
                                              className: "flex items-center"
                                            }, React.createElement("div", {
                                                  className: "flex-shrink-0 h-10 w-10"
                                                }, React.createElement("img", {
                                                      src: EthereumBlockiesBase64(contact.ethAddress)
                                                    })), React.createElement("div", {
                                                  className: "ml-4"
                                                }, React.createElement("div", {
                                                      className: "text-sm font-medium text-gray-900"
                                                    }, contact.name), React.createElement("div", {
                                                      className: "text-sm text-gray-500"
                                                    }, contact.ethAddress)))), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-sm text-black"
                                        }, "None"), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                                        }, React.createElement("button", {
                                              className: "mt-3 w-full inline-flex justify-center border-b-2 border border-black shadow-sm px-4 py-2 bg-white text-base font-medium text-black hover:bg-black hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm rounded"
                                            }, "Delete"))));
                    })));
  } else {
    return React.createElement("p", undefined, "No Contacts");
  }
}

var Contacts = {
  make: ContactsTable$Contacts
};

function ContactsTable(Props) {
  var contactsQuery = Curry.app(Queries$FlowsUserApp.ViewUsers.use, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      ]);
  Curry.app(Queries$FlowsUserApp.RemoveUser.use, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      ]);
  return React.createElement("div", {
              className: "m-2 flex flex-col"
            }, React.createElement("div", {
                  className: "my-2 overflow-x-auto sm:-mx-6 lg:-mx-8"
                }, React.createElement("div", {
                      className: "py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8"
                    }, React.createElement("div", {
                          className: "shadow overflow-hidden border border-black rounded"
                        }, React.createElement(ContactsTable$Contacts, {
                              contactsQuery: contactsQuery
                            })))));
}

var make = ContactsTable;

export {
  Contacts ,
  make ,
  
}
/* react Not a pure module */
