// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function HeadingVarient(Props) {
  var children = Props.children;
  return React.createElement("h1", {
              className: "text-2xl"
            }, children);
}

var make = HeadingVarient;

export {
  make ,
  
}
/* react Not a pure module */
