// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Heading(Props) {
  var children = Props.children;
  return React.createElement("h1", {
              className: "text-3xl font-bold text-center"
            }, children);
}

var make = Heading;

export {
  make ,
  
}
/* react Not a pure module */
