// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.bs.js";
import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import Connectors from "./connectors";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.bs.js";
import * as RootProvider$FlowsUserApp from "../lib/Old/RootProvider.bs.js";

var connectors = Connectors;

function Login(Props) {
  var redirectOnLoginOpt = Props.redirectOnLogin;
  var redirectOnLogin = redirectOnLoginOpt !== undefined ? redirectOnLoginOpt : true;
  var match = RootProvider$FlowsUserApp.useActivateConnector(undefined);
  var activateConnector = match[1];
  var nextPath = "/";
  var optCurrentUser = RootProvider$FlowsUserApp.useCurrentUser(undefined);
  console.log([
        "cunnert User",
        optCurrentUser
      ]);
  React.useEffect((function () {
          if (nextPath !== undefined && optCurrentUser !== undefined && redirectOnLogin) {
            ReasonReactRouter.push(nextPath);
          }
          
        }), [
        nextPath,
        optCurrentUser
      ]);
  return React.createElement("div", undefined, React.createElement("p", undefined, "Use one of the wallet providers below. ", React.createElement("small", undefined, "(Not sure where to go from here? ", React.createElement("a", {
                          href: "https://google.com",
                          rel: "noopener noreferrer",
                          target: "_blank"
                        }, React.createElement("span", undefined, "TODO: put a guide in the blog or something that users can read on if they are confused")), ")")), React.createElement("div", {
                  className: "grid grid-cols-1 gap-2 md:grid-cols-3"
                }, Belt_Array.mapWithIndex(connectors, (function (index, connector) {
                        return React.createElement("div", {
                                    key: String(index),
                                    className: "px-2 border-2 border-black bg-white rounded hover:bg-black hover:text-white",
                                    onClick: (function (e) {
                                        e.stopPropagation();
                                        return Curry._1(activateConnector, connector.connector);
                                      })
                                  }, React.createElement("div", {
                                        className: CssJs.style([
                                              CssJs.margin(CssJs.px(8)),
                                              CssJs.display("flex"),
                                              CssJs.justifyContent("center"),
                                              CssJs.alignItems("center"),
                                              CssJs.flexDirection(CssJs.column),
                                              CssJs.cursor("pointer"),
                                              CssJs.borderRadius(CssJs.px(12)),
                                              CssJs.transition(200, 0, CssJs.easeInOut, "background-color")
                                            ])
                                      }, React.createElement("div", {
                                            className: Curry._1(Css.style, {
                                                  hd: Css.width(Css.px(70)),
                                                  tl: {
                                                    hd: Css.height(Css.px(70)),
                                                    tl: /* [] */0
                                                  }
                                                })
                                          }, React.createElement("img", {
                                                className: Curry._1(Css.style, {
                                                      hd: Css.width({
                                                            NAME: "percent",
                                                            VAL: 100
                                                          }),
                                                      tl: {
                                                        hd: Css.height({
                                                              NAME: "percent",
                                                              VAL: 100
                                                            }),
                                                        tl: /* [] */0
                                                      }
                                                    }),
                                                alt: connector.name,
                                                src: connector.img
                                              })), React.createElement("div", {
                                            className: "text-3xl font-bold m-1"
                                          }, connector.name), React.createElement("div", {
                                            className: "font-large justify-center text-center m-1"
                                          }, connector.connectionPhrase)));
                      }))));
}

var make = Login;

export {
  connectors ,
  make ,
  
}
/* connectors Not a pure module */
